# Generated by Django 5.1.7 on 2025-03-22 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strDescripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='GeneroPelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strDescripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'generopelicula',
            },
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dteFechaInicio', models.DateTimeField()),
                ('dteFechaFin', models.DateTimeField()),
            ],
            options={
                'db_table': 'horarios',
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strNombre', models.CharField(max_length=45)),
                ('strSinopsis', models.CharField(max_length=100)),
                ('AnioEstreno', models.IntegerField()),
                ('duracionMint', models.IntegerField()),
                ('strArchivoFtp', models.CharField(max_length=100)),
                ('strVideo', models.CharField(max_length=100)),
                ('idGenero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.generopelicula')),
            ],
            options={
                'db_table': 'pelicula',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strDescripcion', models.CharField(max_length=45)),
                ('intCantidadAcientos', models.IntegerField()),
                ('idEstado', models.ForeignKey(db_column='idestad', on_delete=django.db.models.deletion.CASCADE, to='peliculas.estado')),
            ],
            options={
                'db_table': 'sala',
            },
        ),
        migrations.CreateModel(
            name='Cartelera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HorarioInicio', models.TimeField()),
                ('HorarioFin', models.TimeField()),
                ('idEstado', models.ForeignKey(db_column='idEsta', on_delete=django.db.models.deletion.CASCADE, to='peliculas.estado')),
                ('idHorarios', models.ForeignKey(db_column='idHorarios', on_delete=django.db.models.deletion.CASCADE, to='peliculas.horarios')),
                ('idPelicula', models.ForeignKey(db_column='idpelicul', on_delete=django.db.models.deletion.CASCADE, to='peliculas.pelicula')),
                ('idSala', models.ForeignKey(db_column='idSal', on_delete=django.db.models.deletion.CASCADE, to='peliculas.sala')),
            ],
            options={
                'db_table': 'cartelera',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strNombre', models.CharField(max_length=45)),
                ('strPwd', models.CharField(max_length=45)),
                ('idEstado', models.ForeignKey(db_column='idEstado', on_delete=django.db.models.deletion.CASCADE, to='peliculas.estado')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
