# Generated by Django 5.1.7 on 2025-04-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token_sesion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='strArchivoFtp',
            field=models.CharField(max_length=255),
        ),
    ]
