# Generated by Django 5.1.7 on 2025-04-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_usuario_token_sesion_usuario_ultimo_login_and_more'),
    ]

    operations = [
    ]
