"""
Django settings for cine project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#^f%wy21kd6+7wlvd_!$v3k@*##(yemxyd5n1+f3ivl6p%al--'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cine',
    'peliculas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', 

    'peliculas.middleware.ExceptionLoggingMiddleware',
    

]

ROOT_URLCONF = 'cine.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cine.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {

    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'railway',      # Nombre de tu BD
    #     'USER': 'root',            # Usuario
    #     'PASSWORD': 'FKIKKsdJDgazUQOoKxSaHEThfmtLDnzi',     # Contraseña (NO la raíz)
    #     'HOST': 'monorail.proxy.rlwy.net',               # URL o IP
    #     'PORT': '3306',                # Puerto
    #     'OPTIONS': {
    #         'ssl': {'ca': '/etc/ssl/cert.pem'},  # Necesario para Railway/Render
    #         'charset': 'utf8mb4',
    #     }
    # }

    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'nuevo_cine',
    #     'USER': 'root',
    #     'PASSWORD': 'vicmajo12',
    #     'HOST': 'localhost',
    #     'PORT': '3306',
    # },


    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'cinevick',  # Nombre de tu BD
    #     'USER': '8jhuwnc5glfxj7fhcztx',  # Copia el usuario que te muestra PlanetScale
    #     'PASSWORD': 'pscale_pw_lPVcn8Qx9MUGZOxfpgSrP6aamAbO494JNjYWV6Omskw',  # La contraseña generada
    #     'HOST': 'aws.connect.psdb.cloud',
    #     'PORT': '3306',
    #     'OPTIONS': {
    #         'ssl': {'ca': '/etc/ssl/cert.pem'},  # ¡Obligatorio!
    #         'charset': 'utf8mb4',
    #     }

    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db16715',  # Nombre de tu BD
        'USER': 'db16715',  # Copia el usuario que te muestra PlanetScale
        'PASSWORD': '4c=EQ_2dg7X?',  # La contraseña generada
        'HOST': 'db16715.public.databaseasp.net',
        'PORT': '3306',
        'OPTIONS': {
            'ssl': {'ca': '/etc/ssl/cert.pem'},  # ¡Obligatorio!
            'charset': 'utf8mb4',
        }

    }
}

    
   



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True
USE_L10N = False
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
import pathlib

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os

FTP_HOST = "Majo12.somee.com"
FTP_USER = "Vick"
FTP_PASS = "Vicmajo12"
FTP_DIR = "/www.Majo12.somee.com"
FTP_URL = "http://Majo12.somee.com"


# # Configuración de conexión FTP
# FTP_SERVER = "ftp://Majo12.somee.com/www.Majo12.somee.com"  # Reemplaza con tu servidor FTP
# FTP_USER = "Vick"  # Reemplaza con tu usuario FTP
# FTP_PASSWORD = "Vicmajo12"  # Reemplaza con tu contraseña FTP
# FTP_UPLOAD_PATH = "/www.Majo12.somee.com/" 

# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_URL = '/media/'


import os

# Carpeta donde se guardarán las imágenes
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuración de archivos estáticos
STATIC_URL = '/static/'

#.....................................................................
# settings.py

# Configuración de Email con Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'josevictormanuel619@gmail.com'  # Tu dirección de Gmail completa
EMAIL_HOST_PASSWORD = 'nmtt atdl fdoh pbqs'  # Pegar aquí la contraseña de aplicación
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  
SERVER_EMAIL = EMAIL_HOST_USER
# Lista de administradores que recibirán los errores
ADMINS = [
    ('vicmajo12', 'josevictormanuel619@gmail.com'),
    ('vick', 'josevictormauel619@gmail.com'),
    ('majo', '23300018@uttt.edu.mx'),
    # Puedes agregar más administradores si es necesario
    # ('Nombre2', 'correo2@gmail.com'),
]

# Configuración avanzada de logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {pathname} Línea:{lineno} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'verbose',
            'include_html': False,  # Cambiar a True si quieres ver el HTML del error
        },
    },
    'loggers': {
        'django': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}
